// src/modules/governance/reactcode/src/components/TaskStatusBadge.tsx
interface TaskStatusBadgeProps {
  status: string;
}

const statusConfig: Record<string, { label: string; color: string }> = {
  proposed: { label: 'Proposed', color: 'bg-gray-100 text-gray-700' },
  voting: { label: 'Voting', color: 'bg-blue-100 text-blue-700' },
  not_started: { label: 'Not Started', color: 'bg-yellow-100 text-yellow-700' },
  in_progress: { label: 'In Progress', color: 'bg-orange-100 text-orange-700' },
  review: { label: 'Review', color: 'bg-purple-100 text-purple-700' },
  completed: { label: 'Completed', color: 'bg-green-100 text-green-700' },
  blocked: { label: 'Blocked', color: 'bg-red-100 text-red-700' },
  cancelled: { label: 'Cancelled', color: 'bg-gray-200 text-gray-600' },
  draft: { label: 'Draft', color: 'bg-gray-100 text-gray-700' },
  active: { label: 'Active', color: 'bg-green-100 text-green-700' },
  archived: { label: 'Archived', color: 'bg-gray-200 text-gray-600' },
};

export default function TaskStatusBadge({ status }: TaskStatusBadgeProps) {
  const config = statusConfig[status] || statusConfig.proposed;

  return (
    <span className={`px-3 py-1 rounded-full text-xs font-medium ${config.color}`}>
      {config.label}
    </span>
  );
}

// src/modules/governance/views/components/partials/TaskStatusBadge.vue
<script setup>
import { defineProps, computed } from 'vue';

const props = defineProps({
  status: {
    type: String,
    required: true
  }
});

const statusConfig = {
  proposed: { label: 'Proposed', color: 'bg-light' },
  voting: { label: 'Voting', color: 'bg-main-small t-main' },
  not_started: { label: 'Not Started', color: 'bg-fourth-small t-fourth' },
  in_progress: { label: 'In Progress', color: 'bg-second-small t-second' },
  review: { label: 'Review', color: 'bg-fifth-small t-fifth' },
  completed: { label: 'Completed', color: 'bg-green-nice t-white' },
  blocked: { label: 'Blocked', color: 'bg-red-nice t-white' },
  cancelled: { label: 'Cancelled', color: 'bg-grey t-white' },
  draft: { label: 'Draft', color: 'bg-light' },
  active: { label: 'Active', color: 'bg-green-nice t-white' },
  archived: { label: 'Archived', color: 'bg-grey t-white' },
  approved: { label: 'Approved', color: 'bg-green-nice t-white' },
  pending: { label: 'Pending', color: 'bg-fourth-small t-fourth' },
  rejected: { label: 'Rejected', color: 'bg-red-nice t-white' },
};

const config = computed(() => statusConfig[props.status] || statusConfig.proposed);
</script>

<template>
  <span :class="`pd-micro pd-x-small radius-regular p-micro t-medium ${config.color}`">
    {{ config.label }}
  </span>
</template>
