// src/modules/governance/reactcode/src/components/VoteForm.tsx
import { useState } from 'react';
import { ThumbsUp, ThumbsDown, Minus } from 'lucide-react';

interface VoteFormProps {
  onSubmit: (vote: 'yes' | 'no' | 'abstain', comment: string) => void;
}

export default function VoteForm({ onSubmit }: VoteFormProps) {
  const [selectedVote, setSelectedVote] = useState<'yes' | 'no' | 'abstain' | null>(null);
  const [comment, setComment] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (selectedVote) {
      onSubmit(selectedVote, comment);
      setSelectedVote(null);
      setComment('');
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div>
        <h4 className="text-sm font-semibold text-gray-900 mb-3">Cast Your Vote</h4>
        <div className="grid grid-cols-3 gap-4">
          <button
            type="button"
            onClick={() => setSelectedVote('yes')}
            className={`flex flex-col items-center justify-center p-6 rounded-lg border-2 transition-all ${
              selectedVote === 'yes'
                ? 'border-green-500 bg-green-50'
                : 'border-gray-200 hover:border-green-300'
            }`}
          >
            <ThumbsUp className={`w-8 h-8 mb-2 ${selectedVote === 'yes' ? 'text-green-600' : 'text-gray-400'}`} />
            <span className={`font-semibold ${selectedVote === 'yes' ? 'text-green-700' : 'text-gray-600'}`}>
              Yes
            </span>
          </button>

          <button
            type="button"
            onClick={() => setSelectedVote('no')}
            className={`flex flex-col items-center justify-center p-6 rounded-lg border-2 transition-all ${
              selectedVote === 'no'
                ? 'border-red-500 bg-red-50'
                : 'border-gray-200 hover:border-red-300'
            }`}
          >
            <ThumbsDown className={`w-8 h-8 mb-2 ${selectedVote === 'no' ? 'text-red-600' : 'text-gray-400'}`} />
            <span className={`font-semibold ${selectedVote === 'no' ? 'text-red-700' : 'text-gray-600'}`}>
              No
            </span>
          </button>

          <button
            type="button"
            onClick={() => setSelectedVote('abstain')}
            className={`flex flex-col items-center justify-center p-6 rounded-lg border-2 transition-all ${
              selectedVote === 'abstain'
                ? 'border-gray-500 bg-gray-50'
                : 'border-gray-200 hover:border-gray-400'
            }`}
          >
            <Minus className={`w-8 h-8 mb-2 ${selectedVote === 'abstain' ? 'text-gray-600' : 'text-gray-400'}`} />
            <span className={`font-semibold ${selectedVote === 'abstain' ? 'text-gray-700' : 'text-gray-600'}`}>
              Abstain
            </span>
          </button>
        </div>
      </div>

      <div>
        <label htmlFor="comment" className="block text-sm font-medium text-gray-700 mb-2">
          Comment (Optional)
        </label>
        <textarea
          id="comment"
          value={comment}
          onChange={(e) => setComment(e.target.value)}
          rows={4}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          placeholder="Share your thoughts on this proposal..."
        />
      </div>

      <button
        type="submit"
        disabled={!selectedVote}
        className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed text-white font-semibold py-3 rounded-lg transition-colors"
      >
        Submit Vote
      </button>
    </form>
  );
}

// src/modules/governance/views/components/partials/VoteForm.vue
<script setup>
import { ref } from 'vue';

const emit = defineEmits(['submit']);

const selectedVote = ref(null);
const comment = ref('');

const handleSubmit = (e) => {
  e.preventDefault();
  if (selectedVote.value) {
    emit('submit', selectedVote.value, comment.value);
    selectedVote.value = null;
    comment.value = '';
  }
};
</script>

<template>
  <form @submit="handleSubmit" class="flex flex-column gap-semi">
    <div>
      <h4 class="p-small t-medium mn-b-small">Cast Your Vote</h4>
      <div class="cols-3 gap-regular">
        <button
          type="button"
          @click="selectedVote = 'yes'"
          :class="`flex flex-column flex-align-center flex-justify-center pd-semi radius-medium br-2px transition-cubic-in-out ${
            selectedVote === 'yes'
              ? 'br-green-nice bg-green-small'
              : 'br-light hover-br-green-nice'
          }`"
        >
          <svg :class="`w-8r h-8r mn-b-thin ${selectedVote === 'yes' ? 'fill-green-nice' : 'fill-grey'}`" viewBox="0 0 24 24" fill="currentColor">
            <path d="M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3zM7 22H4a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h3"/>
          </svg>
          <span :class="`t-medium ${selectedVote === 'yes' ? 't-green-nice' : 't-grey'}`">
            Yes
          </span>
        </button>

        <button
          type="button"
          @click="selectedVote = 'no'"
          :class="`flex flex-column flex-align-center flex-justify-center pd-semi radius-medium br-2px transition-cubic-in-out ${
            selectedVote === 'no'
              ? 'br-red-nice bg-red-small'
              : 'br-light hover-br-red-nice'
          }`"
        >
          <svg :class="`w-8r h-8r mn-b-thin ${selectedVote === 'no' ? 'fill-red-nice' : 'fill-grey'}`" viewBox="0 0 24 24" fill="currentColor">
            <path d="M10 15v4a3 3 0 0 0 3 3l4-9V2H5.72a2 2 0 0 0-2 1.7l-1.38 9a2 2 0 0 0 2 2.3zm7-13h2.67A2.31 2.31 0 0 1 22 4v7a2.31 2.31 0 0 1-2.33 2H17"/>
          </svg>
          <span :class="`t-medium ${selectedVote === 'no' ? 't-red-nice' : 't-grey'}`">
            No
          </span>
        </button>

        <button
          type="button"
          @click="selectedVote = 'abstain'"
          :class="`flex flex-column flex-align-center flex-justify-center pd-semi radius-medium br-2px transition-cubic-in-out ${
            selectedVote === 'abstain'
              ? 'br-grey bg-light'
              : 'br-light hover-br-grey'
          }`"
        >
          <svg :class="`w-8r h-8r mn-b-thin ${selectedVote === 'abstain' ? 'fill-grey' : 'fill-grey'}`" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <line x1="5" y1="12" x2="19" y2="12"/>
          </svg>
          <span :class="`t-medium ${selectedVote === 'abstain' ? 't-grey' : 't-grey'}`">
            Abstain
          </span>
        </button>
      </div>
    </div>

    <div>
      <label for="comment" class="d-block p-small t-medium mn-b-thin">
        Comment (Optional)
      </label>
      <textarea
        id="comment"
        v-model="comment"
        rows="4"
        class="w-100 pd-small br-1px br-light radius-medium"
        style="outline: none; resize: vertical;"
        placeholder="Share your thoughts on this proposal..."
      />
    </div>

    <button
      type="submit"
      :disabled="!selectedVote"
      class="w-100 bg-main hover-bg-main-semi t-white t-medium pd-small radius-medium transition-cubic-in-out"
      :class="{ 'bg-grey cursor-not-allowed': !selectedVote }"
    >
      Submit Vote
    </button>
  </form>
</template>
