// src/modules/governance/views/components/partials/LinkedEntityCard.vue
<script setup>
import { defineProps, computed } from 'vue';
import TaskStatusBadge from './TaskStatusBadge.vue';
import { IconOpenLink, IconCheck } from '@martyrs/src/modules/icons/icons.client.js';

const props = defineProps({
  entityType: {
    type: String,
    required: true,
    validator: (value) => ['initiative', 'milestone', 'task'].includes(value)
  },
  entityData: {
    type: Object,
    required: true
  }
});

const entityConfig = {
  initiative: {
    icon: 'target',
    label: 'Initiative',
    path: (id) => ({ name: 'Initiative', params: { id } }),
  },
  milestone: {
    icon: 'layers',
    label: 'Milestone',
    path: (id) => ({ name: 'Milestone', params: { id } }),
  },
  task: {
    icon: 'checksquare',
    label: 'Task',
    path: (id) => ({ name: 'Task', params: { id } }),
  },
};

const config = computed(() => entityConfig[props.entityType]);
const displayName = computed(() => props.entityData.title || props.entityData.name || 'Untitled');
const routePath = computed(() => config.value.path(props.entityData.id));
</script>

<template>
  <router-link
    :to="routePath"
    class="d-block bg-light radius-medium pd-medium br-1px br-light hover-br-main hover-bg-main-small transition-cubic-in-out"
  >
    <div class="flex flex-justify-between flex-v-start">
      <div class="flex flex-v-start gap-small flex-child-1">
        <div class="bg-white radius-medium pd-thin hover-bg-main-small transition-cubic-in-out">
          <svg v-if="config.icon === 'target'" class="w-5r h-5r t-grey hover-t-main" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10"/>
            <circle cx="12" cy="12" r="6"/>
            <circle cx="12" cy="12" r="2"/>
          </svg>
          <svg v-else-if="config.icon === 'layers'" class="w-5r h-5r t-grey hover-t-main" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <polygon points="12 2 2 7 12 12 22 7 12 2"/>
            <polyline points="2 17 12 22 22 17"/>
            <polyline points="2 12 12 17 22 12"/>
          </svg>
          <svg v-else class="w-5r h-5r t-grey hover-t-main" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <polyline points="9 11 12 14 22 4"/>
            <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>
          </svg>
        </div>
        <div class="flex-child-1 min-w-0">
          <div class="p-micro t-grey mn-b-micro">{{ config.label }}</div>
          <h4 class="p-small t-medium mn-b-thin t-truncate">{{ displayName }}</h4>
          <TaskStatusBadge :status="entityData.status" />
        </div>
      </div>
      <IconOpenLink class="i-small flex-shrink-0 mn-l-thin" :fill="'rgb(var(--grey))'" />
    </div>
  </router-link>
</template>

// src/modules/governance/reactcode/src/components/LinkedEntityCard.tsx
import { Link } from 'react-router-dom';
import { Target, CheckSquare, Layers, ExternalLink } from 'lucide-react';
import TaskStatusBadge from './TaskStatusBadge';

interface LinkedEntityCardProps {
  entityType: 'initiative' | 'milestone' | 'task';
  entityData: {
    id: string;
    name?: string;
    title?: string;
    status: string;
  };
}

const entityConfig = {
  initiative: {
    icon: Target,
    label: 'Initiative',
    path: (id: string) => `/initiatives/${id}`,
  },
  milestone: {
    icon: Layers,
    label: 'Milestone',
    path: (id: string) => `/milestones/${id}`,
  },
  task: {
    icon: CheckSquare,
    label: 'Task',
    path: (id: string) => `/tasks/${id}`,
  },
};

export default function LinkedEntityCard({ entityType, entityData }: LinkedEntityCardProps) {
  const config = entityConfig[entityType];
  const Icon = config.icon;
  const displayName = entityData.title || entityData.name || 'Untitled';

  return (
    <Link
      to={config.path(entityData.id)}
      className="block bg-gray-50 rounded-lg p-4 border border-gray-200 hover:border-blue-300 hover:bg-blue-50 transition-all group"
    >
      <div className="flex items-start justify-between">
        <div className="flex items-start gap-3 flex-1">
          <div className="bg-white rounded-lg p-2 group-hover:bg-blue-100 transition-colors">
            <Icon className="w-5 h-5 text-gray-600 group-hover:text-blue-600" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="text-xs text-gray-500 mb-1">{config.label}</div>
            <h4 className="text-sm font-semibold text-gray-900 mb-2 truncate">{displayName}</h4>
            <TaskStatusBadge status={entityData.status} />
          </div>
        </div>
        <ExternalLink className="w-4 h-4 text-gray-400 group-hover:text-blue-600 flex-shrink-0 ml-2" />
      </div>
    </Link>
  );
}
